# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submited', models.DateField(auto_now_add=True)),
                ('knowledge', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('quality', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('quantity', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('task_and_project_management', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('dependability', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('adaptability_stress_tolerance', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('initiative_resourcefullness', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('judgment_decision_making', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('relationships_with_people_and_communication', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('departmental_college_policies_and_procedures', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('employee_development_and_goal_setting', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3)),
                ('summary_points', models.IntegerField()),
                ('summary_evaluations', models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')])),
                ('improvement_plan_employee', models.TextField()),
                ('improvement_plan_supervisor', models.TextField()),
                ('supervisor_recommendation', models.TextField()),
                ('submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_evaluations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
