# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='departmental_college_policies_and_procedures',
            new_name='departmental_policies_and_procedures',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='adaptability_stress_tolerance',
            field=models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3, verbose_name='Adaptability / stress tolerance'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='initiative_resourcefullness',
            field=models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3, verbose_name='Initiative / resourcefullness'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='judgment_decision_making',
            field=models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], default=3, verbose_name='Judgment / decision making'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='summary_evaluations',
            field=models.IntegerField(choices=[(1, 'Consistently below expectations'), (2, 'Below expectations'), (3, 'Meets expectations'), (4, 'Exceeds expectations'), (5, 'Consistently exceeds expectations')], verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='summary_points',
            field=models.IntegerField(verbose_name='Points'),
        ),
    ]
