# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_auto_20170712_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='summary_evaluations',
            new_name='summary_evaluation',
        ),
    ]
