# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20170712_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='submited',
            field=models.DateField(auto_now=True),
        ),
    ]
