# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_auto_20170708_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=8)),
                ('vehicle_type', models.IntegerField(choices=[(1, 'Moped'), (2, 'Motorcycle'), (3, 'Motor vehicle'), (4, 'Large goods vehicle'), (5, 'Bus')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landline_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('cell_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('certificates', models.TextField()),
                ('other_skills', models.TextField()),
                ('photo', models.ImageField(upload_to=users.models.get_upload_path)),
                ('education', models.IntegerField(choices=[(1, 'None'), (2, 'Elementary school'), (3, 'Middle school'), (4, 'High school')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='departments.Departments')),
                ('driving_licences', models.ManyToManyField(related_name='profiles', to='users.DrivingLicence')),
                ('languages', models.ManyToManyField(related_name='profiles', to='users.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
