# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170709_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivinglicence',
            options={'ordering': ['class_name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
