# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170709_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.get_upload_path),
        ),
    ]
