# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170709_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='driving_licences',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.DrivingLicence'),
        ),
    ]
