import enum


class EmployeeEvaluation(enum.IntEnum):
    CONSISTENTLY_BELOW_EXPECTATIONS = 1
    BELOW_EXPECTATIONS = 2
    MEETS_EXPECTATIONS = 3
    EXCEEDS_EXPECTATIONS = 4
    CONSISTENTLY_EXCEEDS_EXPECTATIONS = 5
