# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deputy_manager', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_department_deputy', to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
