# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='deputy_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_department_deputy', to=settings.AUTH_USER_MODEL),
        ),
    ]
