# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20170708_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['name']},
        ),
    ]
